/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'PaulBaileyToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PaulBaileyToken__factory>
getContractFactory(name: 'ReferralReward', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReferralReward__factory>
getContractFactory(name: 'IDEXRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IDEXRouter__factory>
getContractFactory(name: 'IPaulBaileyToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPaulBaileyToken__factory>
getContractFactory(name: 'IReferralReward', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReferralReward__factory>
getContractFactory(name: 'StakingPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StakingPool__factory>

  getContractAt(name: 'PaulBaileyToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PaulBaileyToken>
getContractAt(name: 'ReferralReward', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReferralReward>
getContractAt(name: 'IDEXRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IDEXRouter>
getContractAt(name: 'IPaulBaileyToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPaulBaileyToken>
getContractAt(name: 'IReferralReward', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReferralReward>
getContractAt(name: 'StakingPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StakingPool>

  deployContract(name: 'PaulBaileyToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PaulBaileyToken>
deployContract(name: 'ReferralReward', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReferralReward>
deployContract(name: 'IDEXRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDEXRouter>
deployContract(name: 'IPaulBaileyToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPaulBaileyToken>
deployContract(name: 'IReferralReward', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReferralReward>
deployContract(name: 'StakingPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingPool>

  deployContract(name: 'PaulBaileyToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PaulBaileyToken>
deployContract(name: 'ReferralReward', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReferralReward>
deployContract(name: 'IDEXRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDEXRouter>
deployContract(name: 'IPaulBaileyToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPaulBaileyToken>
deployContract(name: 'IReferralReward', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReferralReward>
deployContract(name: 'StakingPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingPool>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  