/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as referralRewardSol from './ReferralReward.sol/index.js';
export type { referralRewardSol };
import type * as stakingPoolSol from './StakingPool.sol/index.js';
export type { stakingPoolSol };
export type { PaulBaileyToken } from './PaulBaileyToken.js';
export * as factories from './factories/index.js';
export { PaulBaileyToken__factory } from './factories/PaulBaileyToken__factory.js';
export type { IStakingPool } from './ReferralReward.sol/IStakingPool.js';
export { IStakingPool__factory } from './factories/ReferralReward.sol/IStakingPool__factory.js';
export type { ReferralReward } from './ReferralReward.sol/ReferralReward.js';
export { ReferralReward__factory } from './factories/ReferralReward.sol/ReferralReward__factory.js';
export type { IDEXRouter } from './StakingPool.sol/IDEXRouter.js';
export { IDEXRouter__factory } from './factories/StakingPool.sol/IDEXRouter__factory.js';
export type { IPaulBaileyToken } from './StakingPool.sol/IPaulBaileyToken.js';
export { IPaulBaileyToken__factory } from './factories/StakingPool.sol/IPaulBaileyToken__factory.js';
export type { IReferralReward } from './StakingPool.sol/IReferralReward.js';
export { IReferralReward__factory } from './factories/StakingPool.sol/IReferralReward__factory.js';
export type { StakingPool } from './StakingPool.sol/StakingPool.js';
export { StakingPool__factory } from './factories/StakingPool.sol/StakingPool__factory.js';