/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PaulBaileyTokenInterface extends Interface {
    getFunction(nameOrSignature: "BASE_SLIPPAGE_BPS" | "BURN_ADDRESS" | "DEFLATION_PERCENT_BPS" | "DEFLATION_STOP_SUPPLY" | "INITIAL_SUPPLY" | "allowance" | "approve" | "balanceOf" | "burnShareBps" | "decimals" | "decreaseAllowance" | "deflationActive" | "executeDailyDeflation" | "getEffectiveTaxRate" | "increaseAllowance" | "lastDeflationTime" | "lastRecordedPrice" | "name" | "oracleAddress" | "owner" | "pairAddress" | "priceUpdateTimestamp" | "projectWallet" | "renounceOwnership" | "sell" | "setBurnShare" | "setOracleAddress" | "setPairAddress" | "setProjectWallet" | "setTreasuryWallet" | "symbol" | "timeUntilNextDeflation" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "treasuryWallet" | "updatePriceManually"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "BurnShareUpdated" | "DailyDeflationExecuted" | "OracleAddressUpdated" | "OwnershipTransferred" | "PairAddressSet" | "PriceUpdated" | "ProjectWalletUpdated" | "TokensSold" | "Transfer" | "TreasuryUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_SLIPPAGE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'BURN_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFLATION_PERCENT_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFLATION_STOP_SUPPLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'INITIAL_SUPPLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'burnShareBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'decreaseAllowance', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deflationActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeDailyDeflation', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEffectiveTaxRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'increaseAllowance', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastDeflationTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastRecordedPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracleAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pairAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceUpdateTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'projectWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setBurnShare', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setOracleAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPairAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setProjectWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTreasuryWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'timeUntilNextDeflation', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasuryWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePriceManually', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BASE_SLIPPAGE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BURN_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFLATION_PERCENT_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFLATION_STOP_SUPPLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INITIAL_SUPPLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnShareBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decreaseAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deflationActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeDailyDeflation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEffectiveTaxRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastDeflationTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRecordedPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pairAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceUpdateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBurnShare', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracleAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPairAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProjectWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasuryWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'timeUntilNextDeflation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePriceManually', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnShareUpdatedEvent {
      export type InputTuple = [newBurnShareBps: BigNumberish];
      export type OutputTuple = [newBurnShareBps: bigint];
      export interface OutputObject {newBurnShareBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DailyDeflationExecutedEvent {
      export type InputTuple = [amountRemovedFromPool: BigNumberish, amountBurned: BigNumberish, amountToProject: BigNumberish];
      export type OutputTuple = [amountRemovedFromPool: bigint, amountBurned: bigint, amountToProject: bigint];
      export interface OutputObject {amountRemovedFromPool: bigint, amountBurned: bigint, amountToProject: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleAddressUpdatedEvent {
      export type InputTuple = [newOracle: AddressLike];
      export type OutputTuple = [newOracle: string];
      export interface OutputObject {newOracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PairAddressSetEvent {
      export type InputTuple = [pair: AddressLike];
      export type OutputTuple = [pair: string];
      export interface OutputObject {pair: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceUpdatedEvent {
      export type InputTuple = [newPrice: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [newPrice: bigint, timestamp: bigint];
      export interface OutputObject {newPrice: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectWalletUpdatedEvent {
      export type InputTuple = [newProjectWallet: AddressLike];
      export type OutputTuple = [newProjectWallet: string];
      export interface OutputObject {newProjectWallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensSoldEvent {
      export type InputTuple = [seller: AddressLike, tokenAmount: BigNumberish, usd1Received: BigNumberish, taxAmount: BigNumberish];
      export type OutputTuple = [seller: string, tokenAmount: bigint, usd1Received: bigint, taxAmount: bigint];
      export interface OutputObject {seller: string, tokenAmount: bigint, usd1Received: bigint, taxAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [newTreasury: AddressLike];
      export type OutputTuple = [newTreasury: string];
      export interface OutputObject {newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PaulBaileyToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): PaulBaileyToken;
    waitForDeployment(): Promise<this>;

    interface: PaulBaileyTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_SLIPPAGE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BURN_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFLATION_PERCENT_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFLATION_STOP_SUPPLY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    INITIAL_SUPPLY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    burnShareBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decreaseAllowance: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    deflationActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    executeDailyDeflation: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getEffectiveTaxRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    increaseAllowance: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    lastDeflationTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lastRecordedPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    oracleAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pairAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceUpdateTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projectWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    sell: TypedContractMethod<
      [tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setBurnShare: TypedContractMethod<
      [_burnShareBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setOracleAddress: TypedContractMethod<
      [_oracleAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPairAddress: TypedContractMethod<
      [_pairAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setProjectWallet: TypedContractMethod<
      [_projectWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasuryWallet: TypedContractMethod<
      [_treasuryWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    timeUntilNextDeflation: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasuryWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updatePriceManually: TypedContractMethod<
      [_newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_SLIPPAGE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BURN_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFLATION_PERCENT_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFLATION_STOP_SUPPLY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'INITIAL_SUPPLY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burnShareBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decreaseAllowance'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deflationActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'executeDailyDeflation'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEffectiveTaxRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'increaseAllowance'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastDeflationTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastRecordedPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'oracleAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pairAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceUpdateTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projectWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBurnShare'): TypedContractMethod<
      [_burnShareBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOracleAddress'): TypedContractMethod<
      [_oracleAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPairAddress'): TypedContractMethod<
      [_pairAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProjectWallet'): TypedContractMethod<
      [_projectWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasuryWallet'): TypedContractMethod<
      [_treasuryWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'timeUntilNextDeflation'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasuryWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updatePriceManually'): TypedContractMethod<
      [_newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'BurnShareUpdated'): TypedContractEvent<BurnShareUpdatedEvent.InputTuple, BurnShareUpdatedEvent.OutputTuple, BurnShareUpdatedEvent.OutputObject>;
getEvent(key: 'DailyDeflationExecuted'): TypedContractEvent<DailyDeflationExecutedEvent.InputTuple, DailyDeflationExecutedEvent.OutputTuple, DailyDeflationExecutedEvent.OutputObject>;
getEvent(key: 'OracleAddressUpdated'): TypedContractEvent<OracleAddressUpdatedEvent.InputTuple, OracleAddressUpdatedEvent.OutputTuple, OracleAddressUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PairAddressSet'): TypedContractEvent<PairAddressSetEvent.InputTuple, PairAddressSetEvent.OutputTuple, PairAddressSetEvent.OutputObject>;
getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
getEvent(key: 'ProjectWalletUpdated'): TypedContractEvent<ProjectWalletUpdatedEvent.InputTuple, ProjectWalletUpdatedEvent.OutputTuple, ProjectWalletUpdatedEvent.OutputObject>;
getEvent(key: 'TokensSold'): TypedContractEvent<TokensSoldEvent.InputTuple, TokensSoldEvent.OutputTuple, TokensSoldEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'BurnShareUpdated(uint256)': TypedContractEvent<BurnShareUpdatedEvent.InputTuple, BurnShareUpdatedEvent.OutputTuple, BurnShareUpdatedEvent.OutputObject>;
      BurnShareUpdated: TypedContractEvent<BurnShareUpdatedEvent.InputTuple, BurnShareUpdatedEvent.OutputTuple, BurnShareUpdatedEvent.OutputObject>;
    

      'DailyDeflationExecuted(uint256,uint256,uint256)': TypedContractEvent<DailyDeflationExecutedEvent.InputTuple, DailyDeflationExecutedEvent.OutputTuple, DailyDeflationExecutedEvent.OutputObject>;
      DailyDeflationExecuted: TypedContractEvent<DailyDeflationExecutedEvent.InputTuple, DailyDeflationExecutedEvent.OutputTuple, DailyDeflationExecutedEvent.OutputObject>;
    

      'OracleAddressUpdated(address)': TypedContractEvent<OracleAddressUpdatedEvent.InputTuple, OracleAddressUpdatedEvent.OutputTuple, OracleAddressUpdatedEvent.OutputObject>;
      OracleAddressUpdated: TypedContractEvent<OracleAddressUpdatedEvent.InputTuple, OracleAddressUpdatedEvent.OutputTuple, OracleAddressUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PairAddressSet(address)': TypedContractEvent<PairAddressSetEvent.InputTuple, PairAddressSetEvent.OutputTuple, PairAddressSetEvent.OutputObject>;
      PairAddressSet: TypedContractEvent<PairAddressSetEvent.InputTuple, PairAddressSetEvent.OutputTuple, PairAddressSetEvent.OutputObject>;
    

      'PriceUpdated(uint256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    

      'ProjectWalletUpdated(address)': TypedContractEvent<ProjectWalletUpdatedEvent.InputTuple, ProjectWalletUpdatedEvent.OutputTuple, ProjectWalletUpdatedEvent.OutputObject>;
      ProjectWalletUpdated: TypedContractEvent<ProjectWalletUpdatedEvent.InputTuple, ProjectWalletUpdatedEvent.OutputTuple, ProjectWalletUpdatedEvent.OutputObject>;
    

      'TokensSold(address,uint256,uint256,uint256)': TypedContractEvent<TokensSoldEvent.InputTuple, TokensSoldEvent.OutputTuple, TokensSoldEvent.OutputObject>;
      TokensSold: TypedContractEvent<TokensSoldEvent.InputTuple, TokensSoldEvent.OutputTuple, TokensSoldEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TreasuryUpdated(address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    
    };
  }