/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PaulTokenInterface extends Interface {
    getFunction(nameOrSignature: "BURN_DENOMINATOR" | "BURN_TO_REWARD_RATIO" | "BURN_TO_ZERO_RATIO" | "MAX_SUPPLY" | "ONE_DAY" | "allowance" | "approve" | "balanceOf" | "batchMint" | "burnEnabled" | "burnPercent" | "decimals" | "executeBurn" | "getBurnInfo" | "getBurnableAmounts" | "lastBurnTime" | "mint" | "name" | "nextBurnTime" | "owner" | "renounceOwnership" | "rewardPool" | "setBurnPercent" | "setRewardPool" | "symbol" | "toggleBurn" | "totalBurned" | "totalBurnedToZero" | "totalSentToRewardPool" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "BurnExecuted" | "BurnPercentUpdated" | "BurnToggled" | "Mint" | "OwnershipTransferred" | "RewardPoolUpdated" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'BURN_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'BURN_TO_REWARD_RATIO', values?: undefined): string;
encodeFunctionData(functionFragment: 'BURN_TO_ZERO_RATIO', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SUPPLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'ONE_DAY', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'batchMint', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'burnEnabled', values?: undefined): string;
encodeFunctionData(functionFragment: 'burnPercent', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeBurn', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBurnInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBurnableAmounts', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastBurnTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextBurnTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBurnPercent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRewardPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'toggleBurn', values: [boolean]): string;
encodeFunctionData(functionFragment: 'totalBurned', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalBurnedToZero', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSentToRewardPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BURN_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BURN_TO_REWARD_RATIO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BURN_TO_ZERO_RATIO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SUPPLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ONE_DAY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnPercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeBurn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBurnInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBurnableAmounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastBurnTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextBurnTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBurnPercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'toggleBurn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBurned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBurnedToZero', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSentToRewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnExecutedEvent {
      export type InputTuple = [executor: AddressLike, burnAmount: BigNumberish, burnedToZero: BigNumberish, sentToRewardPool: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [executor: string, burnAmount: bigint, burnedToZero: bigint, sentToRewardPool: bigint, timestamp: bigint];
      export interface OutputObject {executor: string, burnAmount: bigint, burnedToZero: bigint, sentToRewardPool: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnPercentUpdatedEvent {
      export type InputTuple = [oldPercent: BigNumberish, newPercent: BigNumberish];
      export type OutputTuple = [oldPercent: bigint, newPercent: bigint];
      export interface OutputObject {oldPercent: bigint, newPercent: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnToggledEvent {
      export type InputTuple = [enabled: boolean];
      export type OutputTuple = [enabled: boolean];
      export interface OutputObject {enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardPoolUpdatedEvent {
      export type InputTuple = [oldPool: AddressLike, newPool: AddressLike];
      export type OutputTuple = [oldPool: string, newPool: string];
      export interface OutputObject {oldPool: string, newPool: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PaulToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): PaulToken;
    waitForDeployment(): Promise<this>;

    interface: PaulTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BURN_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BURN_TO_REWARD_RATIO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BURN_TO_ZERO_RATIO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SUPPLY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ONE_DAY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    batchMint: TypedContractMethod<
      [recipients: AddressLike[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    burnEnabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    burnPercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    executeBurn: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getBurnInfo: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, string, boolean, bigint, bigint, bigint] & {_burnPercent: bigint, _lastBurnTime: bigint, _nextBurnTime: bigint, _rewardPool: string, _burnEnabled: boolean, _totalBurned: bigint, _totalBurnedToZero: bigint, _totalSentToRewardPool: bigint }],
      'view'
    >
    

    
    getBurnableAmounts: TypedContractMethod<
      [],
      [[bigint, bigint] & {burnToZero: bigint, burnToReward: bigint }],
      'view'
    >
    

    
    lastBurnTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nextBurnTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setBurnPercent: TypedContractMethod<
      [_percent: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRewardPool: TypedContractMethod<
      [_pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    toggleBurn: TypedContractMethod<
      [_enable: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    totalBurned: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalBurnedToZero: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSentToRewardPool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BURN_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BURN_TO_REWARD_RATIO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BURN_TO_ZERO_RATIO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SUPPLY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ONE_DAY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'batchMint'): TypedContractMethod<
      [recipients: AddressLike[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnEnabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'burnPercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executeBurn'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBurnInfo'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, string, boolean, bigint, bigint, bigint] & {_burnPercent: bigint, _lastBurnTime: bigint, _nextBurnTime: bigint, _rewardPool: string, _burnEnabled: boolean, _totalBurned: bigint, _totalBurnedToZero: bigint, _totalSentToRewardPool: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getBurnableAmounts'): TypedContractMethod<
      [],
      [[bigint, bigint] & {burnToZero: bigint, burnToReward: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lastBurnTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextBurnTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setBurnPercent'): TypedContractMethod<
      [_percent: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRewardPool'): TypedContractMethod<
      [_pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'toggleBurn'): TypedContractMethod<
      [_enable: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalBurned'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalBurnedToZero'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSentToRewardPool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'BurnExecuted'): TypedContractEvent<BurnExecutedEvent.InputTuple, BurnExecutedEvent.OutputTuple, BurnExecutedEvent.OutputObject>;
getEvent(key: 'BurnPercentUpdated'): TypedContractEvent<BurnPercentUpdatedEvent.InputTuple, BurnPercentUpdatedEvent.OutputTuple, BurnPercentUpdatedEvent.OutputObject>;
getEvent(key: 'BurnToggled'): TypedContractEvent<BurnToggledEvent.InputTuple, BurnToggledEvent.OutputTuple, BurnToggledEvent.OutputObject>;
getEvent(key: 'Mint'): TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RewardPoolUpdated'): TypedContractEvent<RewardPoolUpdatedEvent.InputTuple, RewardPoolUpdatedEvent.OutputTuple, RewardPoolUpdatedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'BurnExecuted(address,uint256,uint256,uint256,uint256)': TypedContractEvent<BurnExecutedEvent.InputTuple, BurnExecutedEvent.OutputTuple, BurnExecutedEvent.OutputObject>;
      BurnExecuted: TypedContractEvent<BurnExecutedEvent.InputTuple, BurnExecutedEvent.OutputTuple, BurnExecutedEvent.OutputObject>;
    

      'BurnPercentUpdated(uint256,uint256)': TypedContractEvent<BurnPercentUpdatedEvent.InputTuple, BurnPercentUpdatedEvent.OutputTuple, BurnPercentUpdatedEvent.OutputObject>;
      BurnPercentUpdated: TypedContractEvent<BurnPercentUpdatedEvent.InputTuple, BurnPercentUpdatedEvent.OutputTuple, BurnPercentUpdatedEvent.OutputObject>;
    

      'BurnToggled(bool)': TypedContractEvent<BurnToggledEvent.InputTuple, BurnToggledEvent.OutputTuple, BurnToggledEvent.OutputObject>;
      BurnToggled: TypedContractEvent<BurnToggledEvent.InputTuple, BurnToggledEvent.OutputTuple, BurnToggledEvent.OutputObject>;
    

      'Mint(address,uint256)': TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
      Mint: TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RewardPoolUpdated(address,address)': TypedContractEvent<RewardPoolUpdatedEvent.InputTuple, RewardPoolUpdatedEvent.OutputTuple, RewardPoolUpdatedEvent.OutputObject>;
      RewardPoolUpdated: TypedContractEvent<RewardPoolUpdatedEvent.InputTuple, RewardPoolUpdatedEvent.OutputTuple, RewardPoolUpdatedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }