/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPaulBaileyToken, IPaulBaileyTokenInterface } from "../../StakingPool.sol/IPaulBaileyToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenAmount",
        "type": "uint256"
      }
    ],
    "name": "sell",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IPaulBaileyToken__factory {
    static readonly abi = _abi;
    static createInterface(): IPaulBaileyTokenInterface {
      return new Interface(_abi) as IPaulBaileyTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPaulBaileyToken {
      return new Contract(address, _abi, runner) as unknown as IPaulBaileyToken;
    }
  }
  