/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReferralReward, IReferralRewardInterface } from "../../StakingPool.sol/IReferralReward.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "rewardAmount",
        "type": "uint256"
      }
    ],
    "name": "distributeStaticReward",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "onWithdrawClearContribution",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "int256",
        "name": "amountChange",
        "type": "int256"
      },
      {
        "internalType": "bool",
        "name": "isDeposit",
        "type": "bool"
      }
    ],
    "name": "updateTeamPerformance",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IReferralReward__factory {
    static readonly abi = _abi;
    static createInterface(): IReferralRewardInterface {
      return new Interface(_abi) as IReferralRewardInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReferralReward {
      return new Contract(address, _abi, runner) as unknown as IReferralReward;
    }
  }
  