/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStakingPool__factory } from './IStakingPool__factory.js';
export { ReferralReward__factory } from './ReferralReward__factory.js';