/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStakingPool, IStakingPoolInterface } from "../../ReferralReward.sol/IStakingPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getUserInfo",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "principal",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "contribution",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lockUntil",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "pendingRewards",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lastClaimTime",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalDeposited",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IStakingPool__factory {
    static readonly abi = _abi;
    static createInterface(): IStakingPoolInterface {
      return new Interface(_abi) as IStakingPoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStakingPool {
      return new Contract(address, _abi, runner) as unknown as IStakingPool;
    }
  }
  