/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IReferralRewardInterface extends Interface {
    getFunction(nameOrSignature: "distributeStaticReward" | "onWithdrawClearContribution" | "updateTeamPerformance"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'distributeStaticReward', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'onWithdrawClearContribution', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateTeamPerformance', values: [AddressLike, BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'distributeStaticReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onWithdrawClearContribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTeamPerformance', data: BytesLike): Result;
  }

  

  export interface IReferralReward extends BaseContract {
    
    connect(runner?: ContractRunner | null): IReferralReward;
    waitForDeployment(): Promise<this>;

    interface: IReferralRewardInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    distributeStaticReward: TypedContractMethod<
      [user: AddressLike, rewardAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    onWithdrawClearContribution: TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateTeamPerformance: TypedContractMethod<
      [user: AddressLike, amountChange: BigNumberish, isDeposit: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'distributeStaticReward'): TypedContractMethod<
      [user: AddressLike, rewardAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onWithdrawClearContribution'): TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTeamPerformance'): TypedContractMethod<
      [user: AddressLike, amountChange: BigNumberish, isDeposit: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }