/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface StakingPoolInterface extends Interface {
    getFunction(nameOrSignature: "DAILY_DECAY_BPS" | "MIN_DEPOSIT" | "SECONDS_PER_DAY" | "UNCLAIM_EXPIRE_TIME" | "claimRewards" | "deposit" | "dexRouter" | "distributeRewards" | "emergencyWithdrawToken" | "getGlobalDecayInfo" | "getPendingRewards" | "getUserInfo" | "getWithdrawablePrincipal" | "globalDecayFactor" | "isFromPrivateSale" | "lastGlobalDecayUpdate" | "lastRewardDistributionTime" | "owner" | "pblToken" | "pblUsdPair" | "privateSaleContract" | "privateSaleMultiplier" | "referralContract" | "renounceOwnership" | "setPrivateSaleContract" | "setPrivateSaleMultiplier" | "setPrivateSaleUser" | "setReferralContract" | "totalActiveContribution" | "totalRewardToDistribute" | "transferOwnership" | "updateDecay" | "usdToken" | "userStakes" | "withdrawPrincipal"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DailyDecayApplied" | "Deposited" | "LiquidityAdded" | "OwnershipTransferred" | "PrincipalWithdrawn" | "PrivateSaleSet" | "ReferralContractSet" | "RewardsClaimed" | "RewardsDistributed"): EventFragment;

    encodeFunctionData(functionFragment: 'DAILY_DECAY_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DEPOSIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'SECONDS_PER_DAY', values?: undefined): string;
encodeFunctionData(functionFragment: 'UNCLAIM_EXPIRE_TIME', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimRewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'dexRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'distributeRewards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyWithdrawToken', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGlobalDecayInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWithdrawablePrincipal', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'globalDecayFactor', values?: undefined): string;
encodeFunctionData(functionFragment: 'isFromPrivateSale', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastGlobalDecayUpdate', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastRewardDistributionTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pblToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'pblUsdPair', values?: undefined): string;
encodeFunctionData(functionFragment: 'privateSaleContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'privateSaleMultiplier', values?: undefined): string;
encodeFunctionData(functionFragment: 'referralContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPrivateSaleContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPrivateSaleMultiplier', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPrivateSaleUser', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setReferralContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalActiveContribution', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRewardToDistribute', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateDecay', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'userStakes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawPrincipal', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DAILY_DECAY_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DEPOSIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SECONDS_PER_DAY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UNCLAIM_EXPIRE_TIME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dexRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdrawToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGlobalDecayInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWithdrawablePrincipal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'globalDecayFactor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFromPrivateSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastGlobalDecayUpdate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRewardDistributionTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pblToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pblUsdPair', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'privateSaleContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'privateSaleMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'referralContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrivateSaleContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrivateSaleMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrivateSaleUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReferralContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalActiveContribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRewardToDistribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateDecay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userStakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPrincipal', data: BytesLike): Result;
  }

  
    export namespace DailyDecayAppliedEvent {
      export type InputTuple = [newGlobalDecayFactor: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [newGlobalDecayFactor: bigint, timestamp: bigint];
      export interface OutputObject {newGlobalDecayFactor: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [user: AddressLike, usdAmount: BigNumberish, principal: BigNumberish, contributionAdded: BigNumberish, lockUntil: BigNumberish];
      export type OutputTuple = [user: string, usdAmount: bigint, principal: bigint, contributionAdded: bigint, lockUntil: bigint];
      export interface OutputObject {user: string, usdAmount: bigint, principal: bigint, contributionAdded: bigint, lockUntil: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityAddedEvent {
      export type InputTuple = [usdAmount: BigNumberish, pblAmount: BigNumberish, liquidity: BigNumberish];
      export type OutputTuple = [usdAmount: bigint, pblAmount: bigint, liquidity: bigint];
      export interface OutputObject {usdAmount: bigint, pblAmount: bigint, liquidity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrincipalWithdrawnEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrivateSaleSetEvent {
      export type InputTuple = [contractAddress: AddressLike];
      export type OutputTuple = [contractAddress: string];
      export interface OutputObject {contractAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReferralContractSetEvent {
      export type InputTuple = [contractAddress: AddressLike];
      export type OutputTuple = [contractAddress: string];
      export interface OutputObject {contractAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsDistributedEvent {
      export type InputTuple = [totalAmount: BigNumberish];
      export type OutputTuple = [totalAmount: bigint];
      export interface OutputObject {totalAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingPool;
    waitForDeployment(): Promise<this>;

    interface: StakingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DAILY_DECAY_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DEPOSIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SECONDS_PER_DAY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    UNCLAIM_EXPIRE_TIME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimRewards: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    dexRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    distributeRewards: TypedContractMethod<
      [rewardAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyWithdrawToken: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getGlobalDecayInfo: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {decayFactor: bigint, lastUpdate: bigint, totalContribution: bigint }],
      'view'
    >
    

    
    getPendingRewards: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserInfo: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {principal: bigint, contribution: bigint, lockUntil: bigint, pendingRewards: bigint, lastClaimTime: bigint, totalDeposited: bigint }],
      'view'
    >
    

    
    getWithdrawablePrincipal: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    globalDecayFactor: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isFromPrivateSale: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lastGlobalDecayUpdate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lastRewardDistributionTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pblToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pblUsdPair: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    privateSaleContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    privateSaleMultiplier: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    referralContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPrivateSaleContract: TypedContractMethod<
      [_privateSaleContract: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPrivateSaleMultiplier: TypedContractMethod<
      [multiplier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPrivateSaleUser: TypedContractMethod<
      [user: AddressLike, isPrivateSaleUser: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setReferralContract: TypedContractMethod<
      [_referralContract: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalActiveContribution: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRewardToDistribute: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateDecay: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    usdToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    userStakes: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {principal: bigint, contribution: bigint, lastUpdateTime: bigint, lastClaimTime: bigint, lockUntil: bigint, pendingRewards: bigint, contributionSnapshot: bigint, globalDecayFactorSnapshot: bigint, totalDeposited: bigint }],
      'view'
    >
    

    
    withdrawPrincipal: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DAILY_DECAY_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DEPOSIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SECONDS_PER_DAY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'UNCLAIM_EXPIRE_TIME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'dexRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'distributeRewards'): TypedContractMethod<
      [rewardAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdrawToken'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getGlobalDecayInfo'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {decayFactor: bigint, lastUpdate: bigint, totalContribution: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingRewards'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserInfo'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {principal: bigint, contribution: bigint, lockUntil: bigint, pendingRewards: bigint, lastClaimTime: bigint, totalDeposited: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getWithdrawablePrincipal'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'globalDecayFactor'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isFromPrivateSale'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastGlobalDecayUpdate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastRewardDistributionTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pblToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pblUsdPair'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'privateSaleContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'privateSaleMultiplier'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'referralContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPrivateSaleContract'): TypedContractMethod<
      [_privateSaleContract: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPrivateSaleMultiplier'): TypedContractMethod<
      [multiplier: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPrivateSaleUser'): TypedContractMethod<
      [user: AddressLike, isPrivateSaleUser: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setReferralContract'): TypedContractMethod<
      [_referralContract: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalActiveContribution'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRewardToDistribute'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateDecay'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userStakes'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {principal: bigint, contribution: bigint, lastUpdateTime: bigint, lastClaimTime: bigint, lockUntil: bigint, pendingRewards: bigint, contributionSnapshot: bigint, globalDecayFactorSnapshot: bigint, totalDeposited: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawPrincipal'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DailyDecayApplied'): TypedContractEvent<DailyDecayAppliedEvent.InputTuple, DailyDecayAppliedEvent.OutputTuple, DailyDecayAppliedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'LiquidityAdded'): TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PrincipalWithdrawn'): TypedContractEvent<PrincipalWithdrawnEvent.InputTuple, PrincipalWithdrawnEvent.OutputTuple, PrincipalWithdrawnEvent.OutputObject>;
getEvent(key: 'PrivateSaleSet'): TypedContractEvent<PrivateSaleSetEvent.InputTuple, PrivateSaleSetEvent.OutputTuple, PrivateSaleSetEvent.OutputObject>;
getEvent(key: 'ReferralContractSet'): TypedContractEvent<ReferralContractSetEvent.InputTuple, ReferralContractSetEvent.OutputTuple, ReferralContractSetEvent.OutputObject>;
getEvent(key: 'RewardsClaimed'): TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
getEvent(key: 'RewardsDistributed'): TypedContractEvent<RewardsDistributedEvent.InputTuple, RewardsDistributedEvent.OutputTuple, RewardsDistributedEvent.OutputObject>;

    filters: {
      
      'DailyDecayApplied(uint256,uint256)': TypedContractEvent<DailyDecayAppliedEvent.InputTuple, DailyDecayAppliedEvent.OutputTuple, DailyDecayAppliedEvent.OutputObject>;
      DailyDecayApplied: TypedContractEvent<DailyDecayAppliedEvent.InputTuple, DailyDecayAppliedEvent.OutputTuple, DailyDecayAppliedEvent.OutputObject>;
    

      'Deposited(address,uint256,uint256,uint256,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'LiquidityAdded(uint256,uint256,uint256)': TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
      LiquidityAdded: TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PrincipalWithdrawn(address,uint256)': TypedContractEvent<PrincipalWithdrawnEvent.InputTuple, PrincipalWithdrawnEvent.OutputTuple, PrincipalWithdrawnEvent.OutputObject>;
      PrincipalWithdrawn: TypedContractEvent<PrincipalWithdrawnEvent.InputTuple, PrincipalWithdrawnEvent.OutputTuple, PrincipalWithdrawnEvent.OutputObject>;
    

      'PrivateSaleSet(address)': TypedContractEvent<PrivateSaleSetEvent.InputTuple, PrivateSaleSetEvent.OutputTuple, PrivateSaleSetEvent.OutputObject>;
      PrivateSaleSet: TypedContractEvent<PrivateSaleSetEvent.InputTuple, PrivateSaleSetEvent.OutputTuple, PrivateSaleSetEvent.OutputObject>;
    

      'ReferralContractSet(address)': TypedContractEvent<ReferralContractSetEvent.InputTuple, ReferralContractSetEvent.OutputTuple, ReferralContractSetEvent.OutputObject>;
      ReferralContractSet: TypedContractEvent<ReferralContractSetEvent.InputTuple, ReferralContractSetEvent.OutputTuple, ReferralContractSetEvent.OutputObject>;
    

      'RewardsClaimed(address,uint256)': TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
      RewardsClaimed: TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
    

      'RewardsDistributed(uint256)': TypedContractEvent<RewardsDistributedEvent.InputTuple, RewardsDistributedEvent.OutputTuple, RewardsDistributedEvent.OutputObject>;
      RewardsDistributed: TypedContractEvent<RewardsDistributedEvent.InputTuple, RewardsDistributedEvent.OutputTuple, RewardsDistributedEvent.OutputObject>;
    
    };
  }