/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStakingPool } from './IStakingPool.js';
export type { ReferralReward } from './ReferralReward.js';