/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IStakingPoolInterface extends Interface {
    getFunction(nameOrSignature: "getUserInfo"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getUserInfo', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getUserInfo', data: BytesLike): Result;
  }

  

  export interface IStakingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): IStakingPool;
    waitForDeployment(): Promise<this>;

    interface: IStakingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getUserInfo: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {principal: bigint, contribution: bigint, lockUntil: bigint, pendingRewards: bigint, lastClaimTime: bigint, totalDeposited: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getUserInfo'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {principal: bigint, contribution: bigint, lockUntil: bigint, pendingRewards: bigint, lastClaimTime: bigint, totalDeposited: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }