/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ReferralRewardInterface extends Interface {
    getFunction(nameOrSignature: "MAX_GENERATION" | "MIN_VALID_USER_AMOUNT" | "PEER_REWARD_RATE" | "TOTAL_LEVELS" | "authorizedCallers" | "bindReferrer" | "claimLevelReward" | "claimStaticReward" | "distributeStaticReward" | "emergencyWithdrawToken" | "generationRewardRates" | "getPendingRewards" | "getUserLevelInfo" | "getUserReferrals" | "isRegistered" | "isUserValid" | "levelConfigs" | "onWithdrawClearContribution" | "owner" | "renounceOwnership" | "rewardToken" | "setAuthorizedCaller" | "setRewardToken" | "setStakingPool" | "stakingPool" | "totalUsers" | "totalValidUsers" | "transferOwnership" | "updateTeamPerformance" | "users"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorizedCallerSet" | "LevelRewardClaimed" | "LevelUpgraded" | "OwnershipTransferred" | "ReferrerBound" | "StaticRewardClaimed" | "StaticRewardDistributed" | "TeamPerformanceUpdated" | "UserStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_GENERATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_VALID_USER_AMOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'PEER_REWARD_RATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOTAL_LEVELS', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedCallers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'bindReferrer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimLevelReward', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimStaticReward', values?: undefined): string;
encodeFunctionData(functionFragment: 'distributeStaticReward', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyWithdrawToken', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'generationRewardRates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPendingRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserLevelInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserReferrals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isUserValid', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'levelConfigs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'onWithdrawClearContribution', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuthorizedCaller', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setRewardToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setStakingPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stakingPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalUsers', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalValidUsers', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateTeamPerformance', values: [AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'users', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_GENERATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_VALID_USER_AMOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PEER_REWARD_RATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOTAL_LEVELS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedCallers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bindReferrer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimLevelReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimStaticReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeStaticReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdrawToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'generationRewardRates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserLevelInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserReferrals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUserValid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'levelConfigs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onWithdrawClearContribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedCaller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStakingPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalValidUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTeamPerformance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'users', data: BytesLike): Result;
  }

  
    export namespace AuthorizedCallerSetEvent {
      export type InputTuple = [caller: AddressLike, authorized: boolean];
      export type OutputTuple = [caller: string, authorized: boolean];
      export interface OutputObject {caller: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LevelRewardClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, level: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, level: bigint];
      export interface OutputObject {user: string, amount: bigint, level: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LevelUpgradedEvent {
      export type InputTuple = [user: AddressLike, oldLevel: BigNumberish, newLevel: BigNumberish];
      export type OutputTuple = [user: string, oldLevel: bigint, newLevel: bigint];
      export interface OutputObject {user: string, oldLevel: bigint, newLevel: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReferrerBoundEvent {
      export type InputTuple = [user: AddressLike, referrer: AddressLike];
      export type OutputTuple = [user: string, referrer: string];
      export interface OutputObject {user: string, referrer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StaticRewardClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StaticRewardDistributedEvent {
      export type InputTuple = [user: AddressLike, receivers: AddressLike[], amounts: BigNumberish[], generations: BigNumberish[]];
      export type OutputTuple = [user: string, receivers: string[], amounts: bigint[], generations: bigint[]];
      export interface OutputObject {user: string, receivers: string[], amounts: bigint[], generations: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TeamPerformanceUpdatedEvent {
      export type InputTuple = [user: AddressLike, amountChange: BigNumberish, newTotal: BigNumberish, newSmall: BigNumberish];
      export type OutputTuple = [user: string, amountChange: bigint, newTotal: bigint, newSmall: bigint];
      export interface OutputObject {user: string, amountChange: bigint, newTotal: bigint, newSmall: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserStatusUpdatedEvent {
      export type InputTuple = [user: AddressLike, isValid: boolean];
      export type OutputTuple = [user: string, isValid: boolean];
      export interface OutputObject {user: string, isValid: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReferralReward extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReferralReward;
    waitForDeployment(): Promise<this>;

    interface: ReferralRewardInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_GENERATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_VALID_USER_AMOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PEER_REWARD_RATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TOTAL_LEVELS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    authorizedCallers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    bindReferrer: TypedContractMethod<
      [referrerCode: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimLevelReward: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    claimStaticReward: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    distributeStaticReward: TypedContractMethod<
      [user: AddressLike, rewardAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    emergencyWithdrawToken: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    generationRewardRates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPendingRewards: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint] & {staticRewards: bigint, levelRewards: bigint, totalRewards: bigint }],
      'view'
    >
    

    
    getUserLevelInfo: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, boolean, bigint] & {level: bigint, smallTeamPerformance: bigint, totalTeamPerformance: bigint, requiredForNextLevel: bigint, isValidUser: boolean, totalStaticEarned: bigint }],
      'view'
    >
    

    
    getUserReferrals: TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUserValid: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    levelConfigs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {teamPerformance: bigint, rewardRate: bigint }],
      'view'
    >
    

    
    onWithdrawClearContribution: TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAuthorizedCaller: TypedContractMethod<
      [caller: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setRewardToken: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setStakingPool: TypedContractMethod<
      [_stakingPool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    stakingPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalUsers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalValidUsers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateTeamPerformance: TypedContractMethod<
      [user: AddressLike, amountChange: BigNumberish, isDeposit: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    users: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, boolean, bigint, bigint, bigint, bigint, bigint] & {referrer: string, totalTeamPerformance: bigint, smallTeamPerformance: bigint, level: bigint, isValidUser: boolean, pendingStaticRewards: bigint, pendingLevelRewards: bigint, lastUpdateTime: bigint, totalStaticEarned: bigint, totalDeposited: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_GENERATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_VALID_USER_AMOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PEER_REWARD_RATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TOTAL_LEVELS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedCallers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'bindReferrer'): TypedContractMethod<
      [referrerCode: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimLevelReward'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimStaticReward'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeStaticReward'): TypedContractMethod<
      [user: AddressLike, rewardAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdrawToken'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'generationRewardRates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingRewards'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint] & {staticRewards: bigint, levelRewards: bigint, totalRewards: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserLevelInfo'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, boolean, bigint] & {level: bigint, smallTeamPerformance: bigint, totalTeamPerformance: bigint, requiredForNextLevel: bigint, isValidUser: boolean, totalStaticEarned: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserReferrals'): TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUserValid'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'levelConfigs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {teamPerformance: bigint, rewardRate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'onWithdrawClearContribution'): TypedContractMethod<
      [user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAuthorizedCaller'): TypedContractMethod<
      [caller: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRewardToken'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStakingPool'): TypedContractMethod<
      [_stakingPool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalUsers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalValidUsers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTeamPerformance'): TypedContractMethod<
      [user: AddressLike, amountChange: BigNumberish, isDeposit: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'users'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, boolean, bigint, bigint, bigint, bigint, bigint] & {referrer: string, totalTeamPerformance: bigint, smallTeamPerformance: bigint, level: bigint, isValidUser: boolean, pendingStaticRewards: bigint, pendingLevelRewards: bigint, lastUpdateTime: bigint, totalStaticEarned: bigint, totalDeposited: bigint }],
      'view'
    >;

    getEvent(key: 'AuthorizedCallerSet'): TypedContractEvent<AuthorizedCallerSetEvent.InputTuple, AuthorizedCallerSetEvent.OutputTuple, AuthorizedCallerSetEvent.OutputObject>;
getEvent(key: 'LevelRewardClaimed'): TypedContractEvent<LevelRewardClaimedEvent.InputTuple, LevelRewardClaimedEvent.OutputTuple, LevelRewardClaimedEvent.OutputObject>;
getEvent(key: 'LevelUpgraded'): TypedContractEvent<LevelUpgradedEvent.InputTuple, LevelUpgradedEvent.OutputTuple, LevelUpgradedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReferrerBound'): TypedContractEvent<ReferrerBoundEvent.InputTuple, ReferrerBoundEvent.OutputTuple, ReferrerBoundEvent.OutputObject>;
getEvent(key: 'StaticRewardClaimed'): TypedContractEvent<StaticRewardClaimedEvent.InputTuple, StaticRewardClaimedEvent.OutputTuple, StaticRewardClaimedEvent.OutputObject>;
getEvent(key: 'StaticRewardDistributed'): TypedContractEvent<StaticRewardDistributedEvent.InputTuple, StaticRewardDistributedEvent.OutputTuple, StaticRewardDistributedEvent.OutputObject>;
getEvent(key: 'TeamPerformanceUpdated'): TypedContractEvent<TeamPerformanceUpdatedEvent.InputTuple, TeamPerformanceUpdatedEvent.OutputTuple, TeamPerformanceUpdatedEvent.OutputObject>;
getEvent(key: 'UserStatusUpdated'): TypedContractEvent<UserStatusUpdatedEvent.InputTuple, UserStatusUpdatedEvent.OutputTuple, UserStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'AuthorizedCallerSet(address,bool)': TypedContractEvent<AuthorizedCallerSetEvent.InputTuple, AuthorizedCallerSetEvent.OutputTuple, AuthorizedCallerSetEvent.OutputObject>;
      AuthorizedCallerSet: TypedContractEvent<AuthorizedCallerSetEvent.InputTuple, AuthorizedCallerSetEvent.OutputTuple, AuthorizedCallerSetEvent.OutputObject>;
    

      'LevelRewardClaimed(address,uint256,uint256)': TypedContractEvent<LevelRewardClaimedEvent.InputTuple, LevelRewardClaimedEvent.OutputTuple, LevelRewardClaimedEvent.OutputObject>;
      LevelRewardClaimed: TypedContractEvent<LevelRewardClaimedEvent.InputTuple, LevelRewardClaimedEvent.OutputTuple, LevelRewardClaimedEvent.OutputObject>;
    

      'LevelUpgraded(address,uint256,uint256)': TypedContractEvent<LevelUpgradedEvent.InputTuple, LevelUpgradedEvent.OutputTuple, LevelUpgradedEvent.OutputObject>;
      LevelUpgraded: TypedContractEvent<LevelUpgradedEvent.InputTuple, LevelUpgradedEvent.OutputTuple, LevelUpgradedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReferrerBound(address,address)': TypedContractEvent<ReferrerBoundEvent.InputTuple, ReferrerBoundEvent.OutputTuple, ReferrerBoundEvent.OutputObject>;
      ReferrerBound: TypedContractEvent<ReferrerBoundEvent.InputTuple, ReferrerBoundEvent.OutputTuple, ReferrerBoundEvent.OutputObject>;
    

      'StaticRewardClaimed(address,uint256)': TypedContractEvent<StaticRewardClaimedEvent.InputTuple, StaticRewardClaimedEvent.OutputTuple, StaticRewardClaimedEvent.OutputObject>;
      StaticRewardClaimed: TypedContractEvent<StaticRewardClaimedEvent.InputTuple, StaticRewardClaimedEvent.OutputTuple, StaticRewardClaimedEvent.OutputObject>;
    

      'StaticRewardDistributed(address,address[],uint256[],uint256[])': TypedContractEvent<StaticRewardDistributedEvent.InputTuple, StaticRewardDistributedEvent.OutputTuple, StaticRewardDistributedEvent.OutputObject>;
      StaticRewardDistributed: TypedContractEvent<StaticRewardDistributedEvent.InputTuple, StaticRewardDistributedEvent.OutputTuple, StaticRewardDistributedEvent.OutputObject>;
    

      'TeamPerformanceUpdated(address,int256,uint256,uint256)': TypedContractEvent<TeamPerformanceUpdatedEvent.InputTuple, TeamPerformanceUpdatedEvent.OutputTuple, TeamPerformanceUpdatedEvent.OutputObject>;
      TeamPerformanceUpdated: TypedContractEvent<TeamPerformanceUpdatedEvent.InputTuple, TeamPerformanceUpdatedEvent.OutputTuple, TeamPerformanceUpdatedEvent.OutputObject>;
    

      'UserStatusUpdated(address,bool)': TypedContractEvent<UserStatusUpdatedEvent.InputTuple, UserStatusUpdatedEvent.OutputTuple, UserStatusUpdatedEvent.OutputObject>;
      UserStatusUpdated: TypedContractEvent<UserStatusUpdatedEvent.InputTuple, UserStatusUpdatedEvent.OutputTuple, UserStatusUpdatedEvent.OutputObject>;
    
    };
  }